# This is a basic workflow to help you get started with Actions

name: clang check

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: apt install postgresql-14 postgresql-server-dev-14
      - run: cat /usr/lib/postgresql/14/lib/pgxs/src/Makefile.global
      - run: cat /etc/apt/sources.list
      - run: sudo dpkg -l
      - run: printenv
      - run: echo $CC
